-- RAG / 旧 FastAPI 逻辑依赖的表：messages（含 embedding）、diary_entries
-- 与 safebase_backend_cursor/app/models.py 中 Message、DiaryEntry 对齐。
-- user_id 外键指向 auth.users(id)；旧库 public.users 的 id 需与 Supabase Auth 用户 UUID 一致。

create extension if not exists vector;

-- BY DEFAULT：允许数据迁移脚本显式插入旧 id
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  embedding vector(2048),
  created_at timestamptz not null default now()
);

create index if not exists messages_user_created_idx
  on public.messages (user_id, created_at desc);

-- 与 ORDER BY embedding <-> query 一致（L2）；ANN 索引在部分环境可能不可用，失败时仅影响检索加速
do $$
begin
  create index messages_embedding_hnsw_idx
    on public.messages using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64)
    where embedding is not null;
exception
  when others then
    raise notice 'messages HNSW index skipped: %', sqlerrm;
end $$;

do $$
begin
  create index summaries_embedding_hnsw_idx
    on public.summaries using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64)
    where embedding is not null;
exception
  when others then
    raise notice 'summaries HNSW index skipped: %', sqlerrm;
end $$;

do $$
begin
  create index anchors_embedding_hnsw_idx
    on public.anchors using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64)
    where embedding is not null;
exception
  when others then
    raise notice 'anchors HNSW index skipped: %', sqlerrm;
end $$;

create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title varchar(256) not null default '',
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists diary_entries_user_created_idx
  on public.diary_entries (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public.messages enable row level security;
alter table public.diary_entries enable row level security;

drop policy if exists messages_select on public.messages;
drop policy if exists messages_insert on public.messages;
drop policy if exists messages_update on public.messages;
drop policy if exists messages_delete on public.messages;

create policy messages_select on public.messages
  for select to authenticated using (user_id = (select auth.uid()));
create policy messages_insert on public.messages
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy messages_update on public.messages
  for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy messages_delete on public.messages
  for delete to authenticated using (user_id = (select auth.uid()));

drop policy if exists diary_entries_select on public.diary_entries;
drop policy if exists diary_entries_insert on public.diary_entries;
drop policy if exists diary_entries_update on public.diary_entries;
drop policy if exists diary_entries_delete on public.diary_entries;

create policy diary_entries_select on public.diary_entries
  for select to authenticated using (user_id = (select auth.uid()));
create policy diary_entries_insert on public.diary_entries
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy diary_entries_update on public.diary_entries
  for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy diary_entries_delete on public.diary_entries
  for delete to authenticated using (user_id = (select auth.uid()));

revoke all on public.messages from anon, public;
revoke all on public.diary_entries from anon, public;

grant select, insert, update, delete on public.messages to authenticated;
grant select, insert, update, delete on public.diary_entries to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- 审计触发器：扩展 private.audit_row_dml
-- ---------------------------------------------------------------------------

create or replace function private.audit_row_dml()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_subject uuid;
  v_pk text;
  v_op text := tg_op;
  v_table text := tg_table_name;
  v_detail jsonb := '{}'::jsonb;
begin
  if v_table = 'diaries' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'chat_sessions' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'chat_messages' then
    if tg_op = 'DELETE' then
      select s.user_id into v_subject
      from public.chat_sessions s
      where s.id = old.session_id;
      v_pk := old.id::text;
    else
      select s.user_id into v_subject
      from public.chat_sessions s
      where s.id = new.session_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'profiles' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.user_id::text;
    else
      v_subject := new.user_id;
      v_pk := new.user_id::text;
    end if;
  elsif v_table = 'summaries' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'anchors' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'messages' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  elsif v_table = 'diary_entries' then
    if tg_op = 'DELETE' then
      v_subject := old.user_id;
      v_pk := old.id::text;
    else
      v_subject := new.user_id;
      v_pk := new.id::text;
    end if;
  else
    return coalesce(new, old);
  end if;

  if v_subject is null then
    return coalesce(new, old);
  end if;

  if tg_op = 'UPDATE' and v_table = 'diaries' then
    v_detail := jsonb_build_object(
      'title_changed', old.title is distinct from new.title,
      'content_changed', old.content is distinct from new.content
    );
  elsif tg_op = 'UPDATE' and v_table = 'chat_messages' then
    v_detail := jsonb_build_object(
      'content_changed', old.content is distinct from new.content,
      'role', new.role
    );
  elsif tg_op = 'UPDATE' and v_table = 'chat_sessions' then
    v_detail := jsonb_build_object(
      'title_changed', old.title is distinct from new.title
    );
  elsif tg_op = 'UPDATE' and v_table = 'profiles' then
    v_detail := jsonb_build_object(
      'content_changed', old.content is distinct from new.content
    );
  elsif tg_op = 'UPDATE' and v_table = 'summaries' then
    v_detail := jsonb_build_object(
      'content_changed', old.content is distinct from new.content,
      'type', new.type,
      'summary_date', new.summary_date
    );
  elsif tg_op = 'UPDATE' and v_table = 'anchors' then
    v_detail := jsonb_build_object(
      'event_name_changed', old.event_name is distinct from new.event_name,
      'current_thought_changed', old.current_thought is distinct from new.current_thought
    );
  elsif tg_op = 'UPDATE' and v_table = 'messages' then
    v_detail := jsonb_build_object(
      'content_changed', old.content is distinct from new.content,
      'role', new.role,
      'embedding_changed', old.embedding is distinct from new.embedding
    );
  elsif tg_op = 'UPDATE' and v_table = 'diary_entries' then
    v_detail := jsonb_build_object(
      'title_changed', old.title is distinct from new.title,
      'content_changed', old.content is distinct from new.content
    );
  end if;

  insert into public.data_access_audit (
    actor_id, subject_user_id, op, schema_name, table_name, row_pk, detail
  ) values (
    v_actor,
    v_subject,
    case v_op
      when 'INSERT' then 'INSERT'
      when 'UPDATE' then 'UPDATE'
      when 'DELETE' then 'DELETE'
    end,
    'public',
    v_table,
    v_pk,
    v_detail
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists messages_audit_dml on public.messages;
create trigger messages_audit_dml
  after insert or update or delete on public.messages
  for each row execute function private.audit_row_dml();

drop trigger if exists diary_entries_audit_dml on public.diary_entries;
create trigger diary_entries_audit_dml
  after insert or update or delete on public.diary_entries
  for each row execute function private.audit_row_dml();

drop trigger if exists diary_entries_set_updated_at on public.diary_entries;
create trigger diary_entries_set_updated_at
  before update on public.diary_entries
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- delete_my_data
-- ---------------------------------------------------------------------------

create or replace function public.delete_my_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;
  delete from public.chat_sessions where user_id = v_uid;
  delete from public.diaries where user_id = v_uid;
  delete from public.messages where user_id = v_uid;
  delete from public.diary_entries where user_id = v_uid;
  delete from public.summaries where user_id = v_uid;
  delete from public.anchors where user_id = v_uid;
  delete from public.profiles where user_id = v_uid;
  delete from public.data_access_audit
  where subject_user_id = v_uid or actor_id = v_uid;
end;
$$;
